name: Build iOS IPA

  on:
    workflow_dispatch:
    push:
      branches:
        - main

  jobs:
    build-ios:
      name: Build LeqoeHunt iOS App
      runs-on: macos-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '18'

        - name: Install CocoaPods
          run: |
            sudo gem install cocoapods
            pod --version

        - name: Install npm packages
          run: npm install

        - name: Install iOS dependencies
          run: |
            cd ios/App
            pod install

        - name: Build iOS app
          run: |
            cd ios/App
            xcodebuild clean build \
              -workspace App.xcworkspace \
              -scheme App \
              -configuration Release \
              -destination 'generic/platform=iOS' \
              -derivedDataPath build \
              CODE_SIGN_IDENTITY="" \
              CODE_SIGNING_REQUIRED=NO \
              CODE_SIGNING_ALLOWED=NO

        - name: Create IPA package
          run: |
            cd ios/App/build/Build/Products/Release-iphoneos
            mkdir -p Payload
            cp -r App.app Payload/
            zip -r LeqoeHunt.ipa Payload
            mv LeqoeHunt.ipa ~/LeqoeHunt.ipa
            ls -lh ~/LeqoeHunt.ipa

        - name: Upload IPA
          uses: actions/upload-artifact@v3
          with:
            name: LeqoeHunt-iOS-IPA
            path: ~/LeqoeHunt.ipa
            retention-days: 30

        - name: Build Summary
          run: |
            echo "✅ IPA BUILD SUCCESS!"
            echo "📱 App: LeqoeHunt iOS v2.0.0"
            echo "🔽 Download from Actions → Artifacts"
